execution:
  parallel: True
  njobs: -2

pipeline:

  vaccinations:
    get:
      countries:
      skip_countries:
        - Gabon
        - Morocco # Government data doesn't differentiate 1- and 2-dose vaccines so we use WHO instead
        - North Macedonia
        #- South Africa
        - africacdc
        - Guatemala
        # - Ukraine # server down
        - Saint Lucia # switched to paho. previous source not reporting boosters.
        # - Faeroe Islands
        - Austria  # Moved to ECDC
        # - Denmark  # Moved to ECDC
        # - Colombia  # Moved to PAHO
        - Vietnam  # Moved to WHO
        - Sri Lanka  # Moved to WHO
        - Ukraine  # Moved to WHO
    process:
      skip_complete:
        - Pitcairn
      skip_monotonic_check:
      skip_anomaly_check:
        Algeria:
          - date: 2022-02-17
            metrics: total_boosters
        Australia:
          - date: 2021-05-23
            metrics: people_vaccinated
        Bahrain:
          - date: 2021-03-06
            metrics: total_vaccinations
        Bolivia:
          - date: 2021-03-06
            metrics: people_vaccinated
        Brazil:
          - date: 2021-01-21
            metrics: 
            - total_vaccinations
            - people_vaccinated
        Bulgaria:
          - date: 2021-12-14
            metrics: total_boosters
        Luxembourg:
          - date: 2022-04-17
            metrics: people_fully_vaccinated
        Nigeria:
          - date: 2021-06-15
            metrics: people_fully_vaccinated
        United States:
          - date: 2020-12-16
            metrics: people_vaccinated
    generate:
    export:

  testing:
    get:
      countries: 
      skip_countries:
        - Kazakhstan
        - Ukraine
        - Andorra
        #- Jordan
        - Benin
        - Vanuatu #source no longer updated
        - Guatemala #source no longer updated
        - Indonesia #source no longer updated
        - Gibraltar #source no longer updated
    process:
    generate:
    export:
  
  hospitalizations:
    generate:
      countries:
      skip_countries:
        # - South Africa
        # - Israel
        - Spain
        - Argentina
  